Repository LC044/WeChatMsg, pull requests merged in 2024-01, with the labels that each got.

#270 删掉自己写的protobuf；extrabuf提速
  app/DataBase/hard_link.py
  app/DataBase/msg.py
  app/resources/data/template.html
  app/util/compress_content.py
Labels: size:L

#272 更改部分css；修复语音转文字部分问题
  app/DataBase/exporter_html.py
  app/resources/data/template.html
Labels: size:S

#278 文件名称显示成文件路径了，后面什么都打不开。
  app/util/compress_content.py
Labels: size:XS

#303 修复emoji大部分会bug掉的bug
  app/util/emoji.py
Labels: size:L

#311 修复最后一页滑到底点上一页不清空的bug
  app/resources/data/template.html
  requirements.txt
Labels: size:XS, lgtm

#314 🎂 前端更新：重建HTML文件导出模板
  app/DataBase/exporter_html.py
  app/resources/data/template.html
  app/web_ui/templates/christmas.html
  app/web_ui/templates/home.html
  app/web_ui/templates/index.html
  app/web_ui/templates/wordcloud.html
Labels: size:S, lgtm

#325 完成解析转账和音视频通话类型信息的两个后端接口
  app/DataBase/exporter_csv.py
  app/DataBase/exporter_html.py
  app/DataBase/msg.py
  app/DataBase/output.py
  app/DataBase/package_msg.py
  app/ui/chat/chat_info.py
  app/ui/contact/export/export_dialog.py
  app/ui/menu/export.py
  app/util/compress_content.py
Labels: size:L, lgtm
